{% set name = "django-content-settings" %}
{% set version = "0.29.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_content_settings-{{ version }}.tar.gz
  sha256: 617956597b7071fd068ec81715a79597c0274e3bfdbad12f8cc77e94c3239ddf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - content_settings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/occipital/django-content-settings
  doc_url: https://django-content-settings.readthedocs.io/
  summary: Allows users to easily create and manage editable variables directly from the Django admin panel.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
